Models/Match.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Battleship.Models
{
    public class Match
    {
        public string Opponent { get; set; }
        public string[] Fleet { get; set; }
    }
}

Controllers/AuthController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Battleship.Controllers
{
    public class AuthController : Controller
    {
        private class AuthChallengeActionResult : HttpUnauthorizedResult
        {
            public string LoginProvider { get; set; }
            public string RedirectUri { get; set; }

            public AuthChallengeActionResult(string provider, string redirectUri)
            {
                LoginProvider = provider;
                RedirectUri = redirectUri;
            }

            public override void ExecuteResult(ControllerContext context)
            {
                var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
                context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            authenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Game");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult ExternalLogin(string provider)
        {
            return new AuthChallengeActionResult(provider, Url.Action("ExternalLoginCallback"));
        }

        [AllowAnonymous]
        public async Task<ActionResult> ExternalLoginCallback()
        {
            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            var signInManager = HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            var loginInfo = await authenticationManager.GetExternalLoginInfoAsync();
            if (loginInfo != null)
            {
                await signInManager.SignInAsync(ApplicationUser.Create(loginInfo.Email), true, false);
            }

            return RedirectToAction("Index", "Game");
        }
    }
}

Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Battleship.Controllers
{
    public class GameController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View("About");
        }
    }
}

Views/Game/About.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="margin-top: 50px;">
    <h3>About</h3>
    <p>
        A classic game of Battleship built with SignalR to support concurrent users playing the game. This is a personal project used to learn SignalR and Owin.
    </p>
    <br />

    <h3>Technologies</h3>
    <p>
        <ul>
            <li>Typescript</li>
            <li>Owin external authentication (Google provider)</li>
            <li>SignalR</li>
            <li>KnockoutJS</li>
        </ul>
    </p>
</div>
    

Views/Game/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (!Request.IsAuthenticated)
{
    @Html.Partial("_LoginFormPartial");
}
else
{
    @Html.Partial("_GamePartial");
}

Views/Game/_GamePartial.cshtml
<script src="@Url.Content("~/Content/js/lib/jquery.signalR-2.1.2.min.js")"></script>
<script src="signalr/hubs"></script>

<script>
    window.username = "@User.Identity.Name";
</script>

<script data-main="Content/js/Battleship/Game" src="Content/js/lib/require.js"></script>

<div class="battleship-game"></div>

Views/Game/_LoginFormPartial.cshtml
<script data-main="Content/js/Battleship/Demo" src="Content/js/lib/require.js"></script>

<div class="login-form">
    @using (Html.BeginForm("ExternalLogin", "Auth"))
    {
        @Html.AntiForgeryToken()

        <h3>Challenge a friend to a game of Battleship</h3>
        <div>
            <button type="submit" class="btn btn-primary" id="Google" name="provider" value="Google" title="Authenticate using your Google account">
                <i class="fa fa-google-plus fa-lg"></i>&nbsp;&nbsp;&nbsp;&nbsp;Sign in&nbsp;&nbsp;&nbsp;&nbsp;
            </button>
        </div>
    }
</div>

<div class="battleship-demo"></div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Battleship</title>
    <link href="@Url.Content("~/Content/Css/bootstrap.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Css/panel.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Css/game.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Css/board.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Css/fleetpanel.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Css/builderpanel.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Css/lobbypanel.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Css/targettingpanel.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Css/chatpanel.css")" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="@Url.Content("~/Content/js/lib/jquery-2.1.4.min.js")"></script>
    <script src="@Url.Content("~/Content/js/lib/knockout-3.3.0.js")"></script>
    <script src="@Url.Content("~/Content/js/lib/underscore.min.js")"></script>
    <script src="@Url.Content("~/Content/js/lib/bootstrap.min.js")"></script>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="/" class="navbar-brand">Battleship</a>
            </div>

            <ul class="nav navbar-nav">
                <li>
                    <a href="/about">About</a>
                </li>
                <li>
                    <a href="https://bitbucket.org/farmas/battleship" target="_blank">Source</a>
                </li>
                <li>
                    <a href="http://federicosilva.net/" target="_blank">Blog</a>
                </li>
            </ul>

            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Auth", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <p class="navbar-text navbar-right">
                        @User.Identity.Name &nbsp;&nbsp;
                        <button class="btn btn-danger" type="submit">Sign Out</button>
                    </p>
                }

            }
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
</body>
</html>